### ISSUE TITLE
How does the following work?

### ISSUE THREAD

**Issue by code3z** [rishuverma/TwitterBot#3]
The bot seems to follow a lot of people. It retweeted me but didn't follow. How does the following work?

**Comment by code3z** [comment]
Oh, it's followed me now. But I'm still curious; does it follow after a certain streak, or does it follow every person doing 100 days of code? Is the following to help it discover tweets sooner?

**Comment by rishuverma** [comment]
Hi Ian, after the bot retweets the tweets, it uses the Twitter API to follow the user. Sometimes due to some issues at Twitter end the user is not followed, but if someone is on a streak it would definitely follow it even if it missed the first time.
